### PR TITLE
campaign format that allows for lore and challeneges

### PR DESCRIPTION
**Pull request by drivver44**
the goal of this format is to allow several things
1.players the opportunity to learn how to play the game
2. the ability for challenges to appear for both new and experienced players
3. the ability for lore to occur
4. limit campaign unique units to the bare minimum (currently its 1)

### CODE REVIEW

**Comment by Teifion** [comment]
I think this adds some nice options, @PtaQQ what's your thoughts on the content?

My only concern at this stage is the formatting (drivver has told me it was done in google docs as opposed to markdown).

**Comment by drivver44** [comment]
if you want me to reformat it in markdown i can get that done next week(another thing to learn)

**Comment by PtaQQ** [comment]
I have layed down my thought in #campaign. I think it is mergeable for now, though would indeed be nicer if rewritten to md :)

**Comment by drivver44** [comment]
im closing this as it will not be used by me for future use

**Pull request closed without merging**
